// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import RoomFormController from "./room_form_controller.js"
application.register("room-form", RoomFormController)

import RoomListController from "./room_list_controller.js"
application.register("room-list", RoomListController)
